export default {
    zadania: [{
        id: 1,
        title: "Сложение двух числе",
        topic: "Математика",
        class: '11',
        complexity: "1",
        bodyTask: "sadkjruesiljfkldxlrjk5hjlghjldfxrhljg drg heslrg ersg hkle lkdfxhgljrfhdls ghrfj edrgehsjlgh ldj f gsjl hsdfjl; g dfg jldsf gdr gdf ;lgjdf hgjdfhjgdfl; d gjldfh gkjsdf gjl;dfh gldf nlg hdfgh dflhg ldfhgl hdfg hdfl gsd",
        status: false, // статус решения у пользователя.
        answer: 'Правильный ответ .........',
        help: 'Вспомните.......',
        maxScore: 2,
        checkPoint:
            [{text: 'ASD', checked: false},
                {text: 'ASD312', checked: true},
                {text: 'ASDASDASDD', checked: false},],
        addedFile: ["https://example.com/path/to/your/file.pdf",
            "https://example.com/path/to/your/file.pdf",
            "https://example.com/path/to/your/file.pdf",
            "https://example.com/path/to/your/file.pdf",
            "https://example.com/path/to/your/file.pdf"]
    }, {
        id: 2,
        title: "sdrgrsdgsdrgxdrgxrtdht",
        topic: "Физика",
        class: '10',
        complexity: "1",
        bodyTask: "ХРЕН Нужно будет сложить два числа",
        status: true,
    }, {
        id: 3,
        title: "Сложение двух числе",
        topic: "Математика",
        class: '11',
        complexity: "1",
        bodyTask: "Нужно будет сложить два числаФЫ",
        status: true,
    }, {
        id: 4,
        title: "Сложение двух числе",
        topic: "Химия",
        class: '9',
        complexity: "3",
        bodyTask: "Нужно будет свфыложить два ыфвыфвфывфычисла",
        status: false,
    }, {
        id: 5,
        title: "Сложение двух числе",
        topic: "Математика",
        class: '10',
        complexity: "1",
        bodyTask: "Нужно будет сложить два числа",
        status: false,
    }, {
        id: 6,
        title: "Сложение двух числе",
        topic: "Физика",
        class: '9',
        complexity: "1",
        bodyTask: "Нужно будет сложить два числа",
        status: false,
    }, {
        id: 7,
        title: "Сложение двух числе",
        topic: "Математика",
        class: '11',
        complexity: "1",
        bodyTask: "Нужно будет сложить два числа",
        status: false,
    }, {
        id: 8,
        title: "Сложение двух числе",
        topic: "Химия",
        class: '11',
        complexity: "1",
        bodyTask: "Нужно будет сложить два числа",
        status: false,
    },
        {
            id: 9,
            title: "Сложение двух числе",
            topic: "Математика",
            class: '11',
            complexity: "1",
            bodyTask: "sadkjruesiljfkldxlrjk5hjlghjldfxrhljg drg heslrg ersg hkle lkdfxhgljrfhdls ghrfj edrgehsjlgh ldj f gsjl hsdfjl; g dfg jldsf gdr gdf ;lgjdf hgjdfhjgdfl; d gjldfh gkjsdf gjl;dfh gldf nlg hdfgh dflhg ldfhgl hdfg hdfl gsd",
            status: false,
        }, {
            id: 10,
            title: "sdrgrsdgsdrgxdrgxrtdht",
            topic: "Физика",
            class: '10',
            complexity: "1",
            bodyTask: "ХРЕН Нужно будет сложить два числа",
            status: true,
        }, {
            id: 11,
            title: "Сложение двух числе",
            topic: "Математика",
            class: '11',
            complexity: "1",
            bodyTask: "Нужно будет сложить два числаФЫ",
            status: true,
        }, {
            id: 12,
            title: "Сложение двух числе",
            topic: "Химия",
            class: '9',
            complexity: "3",
            bodyTask: "Нужно будет свфыложить два ыфвыфвфывфычисла",
            status: false,
        }, {
            id: 13,
            title: "Сложение двух числе",
            topic: "Математика",
            class: '10',
            complexity: "1",
            bodyTask: "Нужно будет сложить два числа",
            status: false,
        }, {
            id: 14,
            title: "Сложение двух числе",
            topic: "Физика",
            class: '9',
            complexity: "1",
            bodyTask: "Нужно будет сложить два числа",
            status: false,
        }, {
            id: 15,
            title: "Сложение двух числе",
            topic: "Математика",
            class: '11',
            complexity: "1",
            bodyTask: "Нужно будет сложить два числа",
            status: false,
        }, {
            id: 16,
            title: "Сложение двух числе",
            topic: "Химия",
            class: '11',
            complexity: "1",
            bodyTask: "Нужно будет сложить два числа",
            status: false,
        }],
    // Задания во вкладке Мои добавленные задания
    addTask: [{
        id: Date.now(),
        title: "Что-то новое",
        topic: "Химия",
        complexity: "1",
        bodyTask: "Нужно будет сложить два числа",
        whoAdded: 'Я',
        whoChecked: 'Ты',
        statusCheck: true,
    }, {
        id: Date.now(),
        title: "Что-то новое ASD",
        topic: "Химия",
        complexity: "1",
        bodyTask: "Нужно будет сложить два числа",
        whoAdded: 'Ты',
        whoChecked: 'Я',
        statusCheck: false,
    }, {
        id: Date.now(),
        title: "Что-то новое",
        topic: "Химия",
        complexity: "1",
        bodyTask: "Нужно будет сложить два числа",
        whoAdded: '',
        whoChecked: '',
        statusCheck: true,
    }, {
        id: Date.now(),
        title: "Что-то новое",
        topic: "Химия",
        complexity: "1",
        bodyTask: "Нужно будет сложить два числа",
        whoAdded: '',
        whoChecked: '',
        statusCheck: false,
    }, {
        id: Date.now(),
        title: "Что-то новое",
        topic: "Химия",
        complexity: "1",
        bodyTask: "Нужно будет сложить два числа",
        whoAdded: '',
        whoChecked: '',
        statusCheck: false,
    },]
}